# GitHub sponsor setup.
# These are supported funding model platforms

github: vallereya
# patreon: vallereya
# open_collective: vallereya
# ko_fi: vallereya
# buy_me_a_coffee: vallereya
# thanks_dev: vallereya

# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
# liberapay: # Replace with a single Liberapay username
# issuehunt: # Replace with a single IssueHunt username
# lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
# polar: # Replace with a single Polar username
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
